local data = {mod="Pyanodons"}
data.energy = {}
data.energy["offshore-pump"] = {
    energy_type="none",
    energy_type_input="none",
    energy_usage_min=0,
    energy_usage_max=0,
    energy_usage_priority="none",
    energy_consumption=0,
    energy_type_output="none",
    energy_production=0,
    effectivity=1,
    target_temperature=0,
    maximum_temperature=0,
    fluid_usage=0,
    fluid_burns="none",
    fluid_fuel = {name="none", capacity=0},
    fluid_consumption=0,
    fluid_production={name="water", amount=1200},
    pollution=0,
    speed=1200,
    recipe={type="fluid"}
}
data.energy["assembling-machine-1"] = {
    energy_type="burner",
    energy_type_input="burner",
    energy_usage_min=0,
    energy_usage_max=75000,
    energy_usage_priority="none",
    energy_consumption=75000,
    energy_type_output="none",
    energy_production=0,
    effectivity=1,
    target_temperature=0,
    maximum_temperature=0,
    fluid_usage=0,
    fluid_burns="none",
    fluid_fuel = {name="none", capacity=0},
    fluid_consumption=0,
    fluid_production={name="none", amount=0},
    pollution=12,
    speed=1,
    recipe={type="recipe"}
}
data.energy["assembling-machine-2"] = {
    energy_type="burner",
    energy_type_input="burner",
    energy_usage_min=0,
    energy_usage_max=150000,
    energy_usage_priority="none",
    energy_consumption=150000,
    energy_type_output="none",
    energy_production=0,
    effectivity=1,
    target_temperature=0,
    maximum_temperature=0,
    fluid_usage=0,
    fluid_burns="none",
    fluid_fuel = {name="none", capacity=0},
    fluid_consumption=0,
    fluid_production={name="none", amount=0},
    pollution=12,
    speed=2,
    recipe={type="recipe"}
}
data.energy["assembling-machine-3"] = {
    energy_type="burner",
    energy_type_input="burner",
    energy_usage_min=0,
    energy_usage_max=375000,
    energy_usage_priority="none",
    energy_consumption=375000,
    energy_type_output="none",
    energy_production=0,
    effectivity=1,
    target_temperature=0,
    maximum_temperature=0,
    fluid_usage=0,
    fluid_burns="none",
    fluid_fuel = {name="none", capacity=0},
    fluid_consumption=0,
    fluid_production={name="none", amount=0},
    pollution=12,
    speed=4,
    recipe={type="recipe"}
}
data.energy["boiler"] = {
    energy_type="burner",
    energy_type_input="burner",
    energy_usage_min=0,
    energy_usage_max=3701250,
    energy_usage_priority="none",
    energy_type_output="none",
    energy_consumption=3701250,
    energy_production=0,
    effectivity=1,
    target_temperature=250,
    maximum_temperature=0,
    fluid_usage=0,
    fluid_burns="none",
    fluid_fuel = {name="none", capacity=0},
    fluid_consumption=0,
    fluid_production={name="steam", amount=7},--amount=7.5 but rounded
    pollution=30,
    speed=1,
    recipe={name="steam"}
}
data.energy["steam-engine"] = {
    energy_type="electric",
    energy_type_input="fluid",
    energy_usage_min=0,
    energy_usage_max=0,
    energy_usage_priority="secondary-output",
    energy_consumption=7275000,
    energy_type_output="electric",
    energy_production=7275000,
    effectivity=1,
    target_temperature=0,
    maximum_temperature=500,
    fluid_usage=15,
    fluid_burns=false,
    fluid_fuel = {name="steam", capacity=1000},
    fluid_consumption=15,
    fluid_production={name="none", amount=0},
    pollution=0,
    speed=1,
    recipe={type="recipe"}
}
data.energy["heat-exchanger"] = {
    energy_type="heat",
    energy_type_input="heat",
    energy_usage_min=0,
    energy_usage_max=122220000,
    energy_usage_priority="none",
    energy_consumption=122220000,
    energy_type_output="none",
    energy_production=0,
    effectivity=1,
    target_temperature=500,
    maximum_temperature=0,
    fluid_usage=0,
    fluid_burns="none",
    fluid_fuel = {name="none", capacity=0},
    fluid_consumption=0,
    fluid_production={name="steam", amount=120},
    pollution=0,
    speed=1,
    recipe={type="resource"}
}
--[[
data.energy["steam-turbine"] = {
    energy_type="electric",
    energy_type_input="fluid",
    energy_usage_min=0,
    energy_usage_max=0,
    energy_usage_priority="secondary-output",
    energy_consumption=29100000,
    energy_type_output="electric",
    energy_production=291000000,--1191000000 --Steam Turbine can acccept up to 2000 degree steam but there's no way to produce steam hotter than 500 degrees
    effectivity=10,
    target_temperature=0,
    maximum_temperature=2000,
    fluid_usage=60,
    fluid_burns=false,
    fluid_fuel = {name="steam", capacity=1000},
    fluid_consumption=60,
    fluid_production={name="none", amount=0},
    pollution=0,
    speed=1,
    recipe={type="recipe"}
}
--]]
data.energy["nuclear-reactor"] = {
    energy_type="burner",
    energy_type_input="burner",
    energy_usage_min=0,
    energy_usage_max=10000000000,
    energy_usage_priority="none",
    energy_consumption=10000000000,
    energy_type_output="heat",
    energy_production=2000000000,
    effectivity=0.2,
    target_temperature=0,
    maximum_temperature=0,
    fluid_usage=0,
    fluid_burns="none",
    fluid_fuel = {name="none", capacity=0},
    fluid_consumption=0,
    fluid_production={name="none", amount=0},
    pollution=0,
    speed=1,
    recipe={type="recipe"}
}

data.energy["solar-panel"] = {
    energy_type="electric",
    energy_type_input="none",
    energy_usage_min=0,
    energy_usage_max=0,
    energy_usage_priority="solar",
    energy_consumption=0,
    energy_type_output="electric",
    energy_production=60000,
    effectivity=1,
    target_temperature=0,
    maximum_temperature=0,
    fluid_usage=0,
    fluid_burns="none",
    fluid_fuel = {name="none", capacity=0},
    fluid_consumption=0,
    fluid_production={name="none", amount=0},
    pollution=0,
    speed=1,
    recipe={type="recipe"}
}

data.energy["accumulator"] = {
    energy_type="electric",
    energy_type_input="electric",
    energy_usage_min=0,
    energy_usage_max=300000,
    energy_usage_priority="managed-accumulator",
    energy_consumption=300000,
    energy_type_output="electric",
    energy_production=300000,
    effectivity=1,
    target_temperature=0,
    maximum_temperature=0,
    fluid_usage=0,
    fluid_burns="none",
    fluid_fuel = {name="none", capacity=0},
    fluid_consumption=0,
    fluid_production={name="none", amount=0},
    pollution=0,
    speed=1,
    recipe={type="recipe"}
}

data.energy["glassworks-mk01"] = {
    energy_type="fluid",
    energy_type_input="fluid",
    energy_usage_min=0,
    energy_usage_max=10000000,
    energy_usage_priority="none",
    energy_consumption=10000000,
    energy_type_output="none",
    energy_production=0,
    effectivity=1,
    target_temperature=0,
    maximum_temperature=0,
    fluid_usage=0,
    fluid_burns=true,
    fluid_fuel = {name="diesel", capacity=1000},
    fluid_consumption=6.66,
    fluid_production={name="none", amount=0},
    pollution=10,
    speed=1,
    recipe={type="recipe"}
}
data.energy["glassworks-mk02"] = {
    energy_type="fluid",
    energy_type_input="fluid",
    energy_usage_min=0,
    energy_usage_max=30000000,
    energy_usage_priority="none",
    energy_consumption=30000000,
    energy_type_output="none",
    energy_production=0,
    effectivity=1,
    target_temperature=0,
    maximum_temperature=0,
    fluid_usage=0,
    fluid_burns=true,
    fluid_fuel = {name="diesel", capacity=1000},
    fluid_consumption=20,
    fluid_production={name="none", amount=0},
    pollution=10,
    speed=2,
    recipe={type="recipe"}
}
data.energy["glassworks-mk03"] = {
    energy_type="fluid",
    energy_type_input="fluid",
    energy_usage_min=0,
    energy_usage_max=40000000,
    energy_usage_priority="none",
    energy_consumption=40000000,
    energy_type_output="none",
    energy_production=0,
    effectivity=1,
    target_temperature=0,
    maximum_temperature=0,
    fluid_usage=0,
    fluid_burns=true,
    fluid_fuel = {name="diesel", capacity=1000},
    fluid_consumption=26.66,
    fluid_production={name="none", amount=0},
    pollution=10,
    speed=3,
    recipe={type="recipe"}
}
data.energy["glassworks-mk04"] = {
    energy_type="fluid",
    energy_type_input="fluid",
    energy_usage_min=0,
    energy_usage_max=50000000,
    energy_usage_priority="none",
    energy_consumption=50000000,
    energy_type_output="none",
    energy_production=0,
    effectivity=1,
    target_temperature=0,
    maximum_temperature=0,
    fluid_usage=0,
    fluid_burns=true,
    fluid_fuel = {name="diesel", capacity=1000},
    fluid_consumption=33.33,
    fluid_production={name="none", amount=0},
    pollution=10,
    speed=4,
    recipe={type="recipe"}
}
data.energy["oil-boiler-mk01"] = {
    energy_type="fluid",
    energy_type_input="fluid",
    energy_usage_min=0,
    energy_usage_max=14805000,
    energy_usage_priority="none",
    energy_consumption=14805000,
    energy_type_output="none",
    energy_production=0,
    effectivity=2,
    target_temperature=250,
    maximum_temperature=0,
    fluid_usage=0,
    fluid_burns=true,
    fluid_fuel = {name="diesel", capacity=1000},
    fluid_consumption=9.86,
    fluid_production={name="steam", amount=60},
    pollution=30,
    speed=1,
    recipe={type="resource"}
}
data.energy["gasturbinemk01"] = {
    energy_type="electric",
    energy_type_input="fluid",
    energy_usage_min=0,
    energy_usage_max=0,
    energy_usage_priority="secondary-output",
    energy_consumption=118200000,
    energy_type_output="electric",
    energy_production=118200000,
    effectivity=1,
    target_temperature=0,
    maximum_temperature=1000,
    fluid_usage=60,
    fluid_burns=false,
    fluid_fuel = {name="combustion-mixture1", capacity=2000},
    fluid_consumption=60,
    fluid_production={name="none", amount=0},
    pollution=0.05,---0.06 but rounding errors,
    speed=1,
    recipe={type="recipe"}
}
data.energy["gasturbinemk02"] = {
    energy_type="electric",
    energy_type_input="fluid",
    energy_usage_min=0,
    energy_usage_max=0,
    energy_usage_priority="secondary-output",
    energy_consumption=297750000,
    energy_type_output="electric",
    energy_production=297750000,
    effectivity=1,
    target_temperature=0,
    maximum_temperature=2000,
    fluid_usage=75,
    fluid_burns=false,
    fluid_fuel = {name="combustion-mixture1", capacity=2000},
    fluid_consumption=75,
    fluid_production={name="none", amount=0},
    pollution=0.06,
    speed=1,
    recipe={type="recipe"}
}
data.energy["gasturbinemk03"] = {
    energy_type="electric",
    energy_type_input="fluid",
    energy_usage_min=0,
    energy_usage_max=0,
    energy_usage_priority="secondary-output",
    energy_consumption=537300000,
    energy_type_output="electric",
    energy_production=537300000,
    effectivity=1,
    target_temperature=0,
    maximum_temperature=3000,
    fluid_usage=90,
    fluid_burns=false,
    fluid_fuel = {name="combustion-mixture1", capacity=2000},
    fluid_consumption=90,
    fluid_production={name="none", amount=0},
    pollution=0.06,
    speed=1,
    recipe={type="recipe"}
}
data.energy["py-turbine"] = {
    energy_type="electric",
    energy_type_input="fluid",
    energy_usage_min=0,
    energy_usage_max=0,
    energy_usage_priority="secondary-output",
    energy_consumption=19938006000,
    energy_type_output="electric",
    energy_production=19938006000,
    effectivity=1,
    target_temperature=0,
    maximum_temperature=5000,
    fluid_usage=1999,
    fluid_burns=false,
    fluid_fuel = {name="pressured-steam", capacity=2000},
    fluid_consumption=1999.8,
    fluid_production={name="none", amount=0},
    pollution=0.02,
    speed=1,
    recipe={type="recipe"}
}

return data