---@class LuaEvent : EventData
---@field classname string
---@field element LuaGuiElement
---@field action string
---@field item1 string
---@field item2 string
---@field item3 string
---@field item4 string
---@field item5 string
---@field alt boolean
---@field control boolean
---@field shift boolean

---@class ModulePriorityData
---@field name string
---@field value uint

---@class FuelData
---@field name string
---@field temperature number

---@class ModuleEffectsData
---@field speed number
---@field productivity number
---@field consumption number
---@field pollution number

---@class FactoryData
---@field name string
---@field type string
---@field count number
---@field energy number
---@field speed number
---@field fuel string | FuelData
---@field limit number
---Dictionnary {[module.name] : int}
---@field modules {[string] : uint}
---@field effects ModuleEffectsData
---@field cap ModuleEffects
---@field energy_total number
---@field polution_total number
---@field speed_total number
---@field module_priority {[uint] : ModulePriorityData}

---@class BeaconData : FactoryData
---@field combo number
---@field per_factory number
---@field per_factory_constant number

---@class ProductData
---@field name string
---@field type string
---@field count number
---@field state number
---@field input number

---@class RecipeData
---@field id string
---@field index uint
---@field name string
---@field type string
---@field count number
---@field production number
---@field factory FactoryData
---@field beacons {[uint] : BeaconData}
---@field time uint
---@field energy_total number
---@field polution_total number
---@field is_done boolean
---@field base_time uint

---@class ParametersData
---@field effects ModuleEffectsData

---@class BlockData
---@field id string
---@field index number
---@field name string
---@field type string
---@field owner string
---@field count number
---@field power number
---@field pollution_total number
---@field isEnergy boolean
---@field unlinked boolean
---@field by_product boolean
---@field by_factory boolean
---@field by_limit boolean
---@field time number
---@field ingredients {[string] : ProductData}
---@field products {[string] : ProductData}
---@field recipes {[string] : RecipeData | BlockData}

---@class ModelData
---@field id string
---@field index_id number
---@field time number
---@field version number
---@field owner string
---@field block_id number
---@field recipe_id number
---@field resource_id number
---@field block_root BlockData
---@field blocks {[string] : BlockData}
---@field ingredients {[string] : ProductData}
---@field products {[string] : ProductData}
---@field ressources any
---@field summary any
---@field generators any
---@field parameters ParametersData

---@class ThumbnailsColorData
---@field default string
---@field block_default string
---@field block_selected string
---@field block_reverted string
---@field recipe_default string
---@field product_default string
---@field product_driving string
---@field product_overflow string
---@field ingredient_default string
---@field ingredient_driving string
---@field ingredient_overflow string
